# Generated by Django 5.2.5 on 2025-08-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_school_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'whatsapp': 'https://wa.me/256...', 'facebook': '...', 'twitter': '...'}"),
        ),
    ]
