# Generated by Django 5.2.5 on 2025-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_teammember_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='donation',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
