# Generated by Django 5.2.5 on 2025-09-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_donation_goal_amount_donation_raised_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Add social media links: LinkedIn, WhatsApp, Facebook, Twitter, etc.', null=True),
        ),
    ]
