# Generated by Django 5.2.5 on 2025-09-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_mentor_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='impact/hero/')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='impact/sections/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Section',
                'verbose_name_plural': 'Impact Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ImpactCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('counter_type', models.CharField(choices=[('people', 'People Helped'), ('projects', 'Projects Completed'), ('schools', 'Schools Reached'), ('communities', 'Communities Served'), ('volunteers', 'Active Volunteers'), ('funds', 'Funds Raised'), ('custom', 'Custom Counter')], default='custom', max_length=20)),
                ('target_number', models.PositiveIntegerField(help_text='The number to count up to')),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+', 'K', 'M', '%'", max_length=10)),
                ('prefix', models.CharField(blank=True, help_text="e.g., '$', '#'", max_length=10)),
                ('icon_class', models.CharField(default='fas fa-heart', help_text='FontAwesome icon class', max_length=50)),
                ('color_theme', models.CharField(choices=[('primary', 'Primary Green'), ('secondary', 'Golden Yellow'), ('success', 'Success Green'), ('info', 'Info Blue'), ('warning', 'Warning Orange'), ('danger', 'Danger Red'), ('custom', 'Custom Color')], default='primary', max_length=20)),
                ('custom_color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impact Counter',
                'verbose_name_plural': 'Impact Counters',
                'ordering': ['order', 'title'],
            },
        ),
    ]
