# Generated by Django 5.2.5 on 2025-09-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_impact_impactcounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='hero_image',
        ),
    ]
