# Generated by Django 5.2.5 on 2025-09-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_remove_impact_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='highlight_1_description',
            field=models.CharField(blank=True, help_text="e.g., 'New digital literacy centers established in rural schools'", max_length=200),
        ),
        migrations.AddField(
            model_name='impact',
            name='highlight_1_number',
            field=models.CharField(blank=True, help_text="e.g., '20', '5,000+', '90%'", max_length=50),
        ),
        migrations.AddField(
            model_name='impact',
            name='highlight_2_description',
            field=models.CharField(blank=True, help_text="e.g., 'Youth trained in basic computer skills and internet safety'", max_length=200),
        ),
        migrations.AddField(
            model_name='impact',
            name='highlight_2_number',
            field=models.CharField(blank=True, help_text="e.g., '5,000+', '90%', '15'", max_length=50),
        ),
        migrations.AddField(
            model_name='impact',
            name='highlight_3_description',
            field=models.CharField(blank=True, help_text="e.g., 'of trained youth report increased confidence in using digital tools'", max_length=200),
        ),
        migrations.AddField(
            model_name='impact',
            name='highlight_3_number',
            field=models.CharField(blank=True, help_text="e.g., '90%', '100%', '25'", max_length=50),
        ),
    ]
