# Generated by Django 5.2.5 on 2025-09-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_impact_highlight_1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clubs', 'Best Performing Clubs'), ('mentors', 'Best Performing Mentors'), ('projects', 'Best Performing Projects'), ('programs', 'Best Performing Programs')], max_length=50, unique=True)),
                ('title', models.CharField(help_text='Display title for this spotlight section', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle/description', max_length=300)),
                ('icon_class', models.CharField(default='fas fa-star', help_text='FontAwesome icon class', max_length=50)),
                ('background_color', models.CharField(default='#1A685B', help_text='Hex color code for section background', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on spotlight page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spotlight Category',
                'verbose_name_plural': 'Spotlight Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpotlightStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(help_text="e.g., '150+', '95%', '2.5K'", max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('icon_class', models.CharField(default='fas fa-trophy', max_length=50)),
                ('color', models.CharField(default='#1A685B', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spotlight Statistic',
                'verbose_name_plural': 'Spotlight Statistics',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpotlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Role, location, or brief description', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of achievements and performance')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spotlight/images/')),
                ('performance_level', models.CharField(choices=[('excellent', 'Excellent Performance'), ('outstanding', 'Outstanding Performance'), ('exceptional', 'Exceptional Performance'), ('top_performer', 'Top Performer')], default='excellent', max_length=20)),
                ('achievement_score', models.PositiveIntegerField(default=0, help_text='Numeric score for ranking (higher = better)')),
                ('key_achievements', models.TextField(blank=True, help_text='List key achievements (one per line)')),
                ('location', models.CharField(blank=True, help_text='Location or school (for clubs/projects)', max_length=200)),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Contact details or social links')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured item with special styling')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='charity.spotlightcategory')),
            ],
            options={
                'verbose_name': 'Spotlight Item',
                'verbose_name_plural': 'Spotlight Items',
                'ordering': ['category', 'order', '-achievement_score', 'title'],
            },
        ),
    ]
