# Generated by Django 5.2.5 on 2025-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_projectachievement_projectphoto_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceofchange',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
