# Generated by Django 5.2.5 on 2025-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_voiceofchange_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/images/'),
        ),
    ]
