# Generated by Django 5.2.5 on 2025-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_club_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='Unnamed Mentor', help_text="Mentor's full name", max_length=150),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='title',
            field=models.CharField(help_text="Mentor's role/position/expertise area", max_length=200),
        ),
    ]
