# Generated by Django 5.2.5 on 2025-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_add_mentor_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional subscriber name', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subscription is active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_source', models.CharField(default='website', help_text='Where they subscribed from', max_length=50)),
                ('interests', models.CharField(blank=True, help_text='Areas of interest (comma-separated)', max_length=200)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
