# Generated by Django 5.1.4 on 2025-09-06 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_newslettersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Blog Post (Admin)', 'verbose_name_plural': 'Blog Posts (Admin)'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='details',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='Content to be updated', help_text='Blog post content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(help_text='Admin author name', max_length=150),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(help_text='Article content')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article (Member)',
                'verbose_name_plural': 'Articles (Members)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
