# Generated by Django 5.1.4 on 2025-09-06 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0016_alter_blogpost_options_remove_blogpost_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['school__name', 'title']},
        ),
        migrations.RemoveField(
            model_name='club',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='school',
            name='comment',
        ),
        migrations.AddField(
            model_name='club',
            name='coordinator',
            field=models.CharField(blank=True, help_text='Club coordinator/leader', max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, help_text='Club description and activities'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this club currently active'),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_schedule',
            field=models.CharField(blank=True, help_text="When the club meets (e.g., 'Every Friday 3-5 PM')", max_length=200),
        ),
        migrations.AddField(
            model_name='club',
            name='member_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of active members'),
        ),
        migrations.AddField(
            model_name='club',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this club belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='charity.school'),
        ),
        migrations.AddField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='badge',
            field=models.ImageField(blank=True, help_text='School badge/logo', null=True, upload_to='schools/badges/'),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person at school', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description about the school'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this partnership currently active'),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, help_text='School location/address', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='partnership_date',
            field=models.DateField(blank=True, help_text='When partnership began', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='student_population',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of students', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, help_text='School website'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Blog post content'),
        ),
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.ImageField(blank=True, help_text='Club icon/logo', null=True, upload_to='clubs/icons/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, help_text='Club photo', null=True, upload_to='clubs/images/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, help_text='Club meeting location', max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(help_text='Club name', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, help_text='School photo', null=True, upload_to='schools/photos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='School name', max_length=200),
        ),
    ]
