# Generated by Django 5.1.4 on 2025-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_alter_club_options_remove_club_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, help_text='School website (e.g., www.school.com or https://school.com)', max_length=200),
        ),
    ]
