# Generated by Django 5.2.5 on 2025-09-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_opportunity_projectmembershiprequest_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='opportunities/applications/cv/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='charity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Application',
                'verbose_name_plural': 'Opportunity Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
